home/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name  = 'home'
urlpatterns = [
    path('',home_page,name='home'),
    path('search/',search_results,name='search'),
    path('details/<str:uid>/', details , name='detail'),
    path('check_avail/' , room_availability,name="check_room_avail"),
    path('book-hotel/<str:uid>',booking,name='booking'),
    path('booking-detail/<str:uid>/',bookingdetail,name='booking_detail'),
    path('about-us/',AboutUs,name='about_us'),
    path('contact-us/',ContactUs,name='contact_us'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

hotel/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [   
    path('' , include('home.urls')),
    path('payment/', include('payment.urls')), 
    path('auth/', include('auth_app.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('admin/', admin.site.urls),

]

payment/urls.py
from django.urls import path
from . import views


app_name  = 'payment'
urlpatterns = [
  
  path('booking-history/',views.booking_history,name='booking-history'),
  path('booking-history-detail/<str:uid>/',views.booking_history_detail,name='booking_history_detail'),
  path('checkout-session/<str:uid>/',views.create_stripe_checkout_session,name='checkout-session'),
  path('success/',views.SuccessView.as_view(),name='success'),
  path('cancel/',views.CancelView.as_view(),name='cancel'),
  path('webhook/',views.StripeWebhookView.as_view(),name='webhook'),
  

]

home/models.py
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
import uuid
from smart_selects.db_fields import ChainedForeignKey
from cities_light.models import City, Country, Region
from django.http import JsonResponse,HttpResponse
from django.conf import settings

class BaseModel(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False , primary_key=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now_add=True)

    class Meta:
        abstract = True




class Amenities(BaseModel):
    amenity_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.amenity_name




class Hotel(BaseModel):
    CONTINENT_CHOICES = [
        ('AF', 'Africa'),
        ('AN', 'Antarctica'),
        ('AS', 'Asia'),
        ('EU', 'Europe'),
        ('NA', 'North America'),
        ('OC', 'Oceania'),
        ('SA', 'South America'),
    ]

    hotel_name= models.CharField(max_length=100)
    hotel_email=models.EmailField(default='your@mail.com')
    hotel_phone=models.CharField(max_length=15,default='9876543210')
    hotel_description = models.TextField()
    hotel_amenities = models.ManyToManyField(Amenities)
    # hotel_rooms=models.ManyToManyField('Room',related_name='hotel_rooms')
    total_room = models.IntegerField(default=0)
    total_booked_room=models.IntegerField(default=0)
    total_staffs=models.IntegerField(default=10)
    is_avail=models.BooleanField(default=True)
    #Address
    continent = models.CharField(max_length=2, choices=CONTINENT_CHOICES)
    country = ChainedForeignKey(Country,chained_field="continent",chained_model_field="continent",show_all=False, on_delete=models.CASCADE)
    region= ChainedForeignKey(Region,chained_field="country",chained_model_field="country_id",show_all=False,on_delete=models.CASCADE)
    city = ChainedForeignKey(City, chained_field="region",chained_model_field="region_id",show_all=False,on_delete=models.CASCADE)
    street=models.CharField(max_length=100)
    landmark=models.CharField(max_length=100,default='GMT')
    zip_code=models.CharField(max_length=20,default='000000')


    def __str__(self) -> str:
        return self.hotel_name   

    def is_hotel_available(self):
        return True if self.total_room > self.total_booked_room else False
    
    def total_client(self):
        return 1000 + self.total_booked_room

class Room_Type(BaseModel):
    OTHERS='O'
    SINGLE='SL'
    DOUBLE='D'
    DELUX='DD'
    SUITE='ST'
    DOORMATORY='DT'
    ROOM_CHOICES=[
        ('SINGLE',('Single')),
        ('DOUBLE',('Double')),
       ('DELUX',('Delux')),
       ('SUITE',('Suite')),
       ('DOORMATORY',('Doormatory')),
       ('OTHERS',('Others'))
    ]
   
    type=models.CharField(max_length=10,choices=ROOM_CHOICES)
    room_description=models.TextField()
    room_image=models.ImageField(upload_to="room_type_images")
    facilities=models.ManyToManyField(Amenities)
    max_occupancy=models.IntegerField(default=1)
    

    def __str__(self) -> str:
        return self.type


 
class Room(BaseModel):   
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE,related_name='related_hotel_name',default="")
    rooms_type=models.ForeignKey(Room_Type, on_delete=models.CASCADE)
    room_number=models.IntegerField(default=1)
    floor=models.CharField(max_length=10)
    price=models.DecimalField(decimal_places=2,default=999.00,max_digits=10)
    room_count=models.IntegerField(default=10)
    room_image=models.ImageField(upload_to="room_image" ,default='loading.gif')
    booked_room=models.IntegerField(default=0)
    is_available=models.BooleanField(default=True)

    def available(self):
        totalroom=self.hotel.total_room
        if self.booked_room >= self.totalroom:
            self.is_available=False
        return self.is_available

        

    def __str__(self) -> str:
        return f'Rooms of {self.hotel.hotel_name}'
    
    def save(self, *args, **kwargs):
        self.room_number +=1
        
      
        super().save(*args, **kwargs)
 
 

class HotelImages(BaseModel):
    hotel= models.ForeignKey(Hotel ,related_name="images", on_delete=models.CASCADE)
    images = models.ImageField(upload_to="hotels")


class HotelBooking(BaseModel):
    hotel= models.ForeignKey(Hotel, related_name="hotel_booking_detail" , on_delete=models.PROTECT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="user_booking_detail" , on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    room_type=models.ForeignKey(Room_Type,on_delete=models.PROTECT,related_name='booked_room_type',default=0)
    amount=models.DecimalField(default=0.00,decimal_places=2,max_digits=10)
    booking_type = models.CharField(max_length=100, choices=(('Pre Paid', 'Pre Paid'), ('Post Paid', 'Post Paid')))
    no_of_room = models.IntegerField(default=1)
    room_number=models.IntegerField(blank=True, null=True)
    no_of_people=models.IntegerField()
    customer_desc=models.CharField(max_length=100)


    def __str__(self):
        return f"{self.user}'s booked a room at {self.hotel.hotel_name}"
    
    def save(self, *args, **kwargs):
        # Get all the bookings for this hotel during the same time period
     
        conflicting_bookings = HotelBooking.objects.filter(
            hotel=self.hotel,
            start_date__lte=self.end_date,
            end_date__gte=self.start_date,
        ).exclude(uid=self.uid)
       
        
        # Find the next available room number for this booking
        last_booking = HotelBooking.objects.filter(hotel=self.hotel).order_by('-room_number').first()
        next_room_number = (last_booking.room_number + 1) if last_booking else 1
        
        # Assign the next available room number to this booking
        self.room_number = next_room_number
        self.hotel.total_room -=self.no_of_room
        # Call the superclass's save method to save the booking to the database
        super().save(*args, **kwargs)
    

home/forms.py
from django import forms
from .models import HotelBooking

class HotelBookingForm(forms.ModelForm):
    class Meta:
        model = HotelBooking
        fields = ['start_date', 'end_date', 'room_type', 'booking_type', 'no_of_room','no_of_people','customer_desc']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

home/views.py
from decimal import Decimal
from django.shortcuts import render , redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login,logout
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from .models import (Amenities, Hotel, HotelBooking,Room_Type,Room)
from django.db.models import Q
from django.conf import settings
import stripe
from .forms import HotelBookingForm
from django.contrib.auth.decorators import login_required
from payment.models import BookingDetail
from django.db import models
from django.utils.dateparse import parse_date
from django.db.models import F
from datetime import datetime


stripe.api_key = settings.STRIPE_SECRET_KEY

def check_booking(start_date ,end_date ,uid ,rooms, room_count):
    if(len(HotelBooking.objects.all())<1):
        return True
    check_in_date = (start_date)
    check_out_date = (end_date)
    qs = HotelBooking.objects.filter(   
        start_date__lte=check_in_date,
        end_date__gte=check_out_date,
        hotel__uid = uid
        )
    
    # Calculate the total number of rooms already booked during the date range
    total_booked_rooms = qs.aggregate(models.Sum('no_of_room'))['no_of_room__sum'] or 0
    # Check if the hotel has enough available rooms
    return total_booked_rooms + int(rooms) <= room_count

## New Code Start
def home_page(request):
    return render(request , 'landing_page.html' )

def search_results(request):
    query = request.GET.get('query')
    amenities = Amenities.objects.all()
    if query:
        hotels = Hotel.objects.filter(
            Q(hotel_name__icontains=query) |
            Q(hotel_description__icontains=query)|
            Q(continent__icontains=query) |
            Q(country__name__icontains=query) |
            Q(region__name__icontains=query) |
            Q(city__name__icontains=query) |
            Q(landmark__icontains=query) 
        ).distinct()

        context = {
            'hotels': hotels,
            'query': query,
            'amenities':amenities
        }
        return render(request,'search_results.html',context)

@login_required
def details(request,uid):
    hotels=Hotel.objects.get(uid=uid)
    room_type = Room_Type.objects.filter(room__hotel=hotels).distinct()
    room=Room.objects.filter(hotel=hotels)
    form = HotelBookingForm()
    context={
        'hotels':hotels,
        'room_type':room_type,
        'room':room,
        'form':form,
    }
    return render(request,'details.html',context)


def room_availability(request):
    if request.method=='POST':
        uid=request.POST.get('uid')
        if uid is None:
            return JsonResponse({"error": "No hotel_id provided"})
        checkin = request.POST.get('check_in')
        checkout = request.POST.get('check_out')
        rooms = int(request.POST.get('room_count'))
        room_type=request.POST.get('room_type')

        try:
            hotel = Hotel.objects.get(uid=uid)
        except Hotel.DoesNotExist:
            return JsonResponse({"error": "Hotel not found"})
        # Check if the hotel has enough available rooms for the given date range and room count
        print("checkin: ",checkin)
        check_in = datetime.strptime(checkin, '%m/%d/%Y %I:%M %p')
        check_in_date = check_in.strftime('%Y-%m-%d')
        check_out = datetime.strptime(checkout, '%m/%d/%Y %I:%M %p')
        check_out_date = check_out.strftime('%Y-%m-%d')
        available = check_booking(check_in_date, check_out_date, uid, rooms, hotel.total_room)
        if not available:
            messages.warning(request, 'Hotel is already booked in these dates !!! Please Wait for some time or Try another dates !')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        messages.success(request,"Congrats,Hotel is available in these dates! Book Now")
        return JsonResponse({"available": available,"message":"Congrats,Room is available! Book Now"})
    return JsonResponse({"error": "Invalid request method"})
@login_required
def book_hotel(request):
    if request.method == 'POST':
        uid=request.POST.get('uid')
        hotel =Hotel.objects.get(uid=uid)
        form = HotelBookingForm(request.POST)
        if form.is_valid():
            # Save the booking data to the database
            booking = form.save(commit=False)
            booking.hotel=hotel
            booking.user = request.user # Assuming you have a User model and want to associate the booking with the current user
            booking.save()
            # Redirect the user to the booking detail page
            return redirect('booking_detail', pk=booking.pk)
    else:
        # If the request is not a POST request, create a new empty form
        form = HotelBookingForm()
    # Render the hotel detail template with the booking form included in the modal
    return render(request, 'hotel_booking.html', {'form': form,'pk':booking.pk})
 
def booking(request,uid):
    try:
        hotel = Hotel.objects.get(uid=uid)
        print("hotel: ",hotel)
    except Hotel.DoesNotExist:
        return JsonResponse({"error": "Hotel not found"})
    rooms = Room_Type.objects.filter(room__hotel=hotel).distinct()
    
    if request.method == 'POST':
        # get form data
    
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        room_type_name = request.POST.get('room_type')
        booking_type = request.POST.get('booking_type')
        no_of_room = int(request.POST.get('no_of_room'))
        no_of_people = request.POST.get('no_of_people')
        customer_desc = request.POST.get('customer_desc')

        check_in_date = parse_date(start_date)
        check_out_date = parse_date(end_date)
        

        # Calculate the number of nights between the check-in and check-out dates
        night_count = (check_out_date - check_in_date).days
        
        # Get the selected room object
        room = Room.objects.filter(hotel=hotel, rooms_type__type=room_type_name).first()
        room_type = Room_Type.objects.get(type=room_type_name)
        # Check if the room is available for the selected date range and room count
        available_count = room.room_count - room.booked_room
        if available_count < no_of_room:
            messages.error(request, f'Sorry, there are not enough available {room_type} rooms for the selected date range and room count.')
            return redirect('home:booking' ,hotel.uid)
        amount=room.price * night_count * no_of_room
        if booking_type == 'Pre Paid':
            amount = amount * Decimal('0.9')
        # create hotel booking instance
        hotel_booking = HotelBooking(
            hotel=hotel,
            user=request.user,
            start_date=start_date,
            end_date=end_date,
            room_type=room_type,
            amount=amount,
            booking_type=booking_type,
            no_of_room=no_of_room,
            no_of_people=no_of_people,
            customer_desc=customer_desc
        )
        # save hotel booking instance
        hotel_booking.save()
        print("Booking Data Saved")
        # redirect to booking detail page
        return redirect('home:booking_detail', uid=hotel_booking.uid)
    return render(request, 'booking_form.html', {'hotel': hotel, 'room_type': rooms})


@login_required
def bookingdetail(request, uid):
    booking = get_object_or_404(HotelBooking, uid=uid, user=request.user)
    end_datetime = datetime.combine(booking.end_date, datetime.min.time())
    start_datetime = datetime.combine(booking.start_date, datetime.min.time())
    total_days = (end_datetime - start_datetime).days 
    price = booking.amount
    rooms=booking.no_of_room
    obj=BookingDetail.objects.create(
        hotel=booking.hotel.hotel_name,
        user=request.user,
        start_date=booking.start_date,
        end_date=booking.end_date,
        total_days=total_days,
        total_room=rooms,
        total_amount=price,
        alloted_rooms=booking.room_number
        )
    return render(request, 'booking_detail.html', {'booking': booking,'uid':obj.uid})       


def AboutUs(request):
    return render(request,'about_us.html')

def ContactUs(request):
    return render(request,'contact_us.html')

''' New Codes End '''

def home(request):
    amenities_objs = Amenities.objects.all()
    hotels_objs = Hotel.objects.all()

    sort_by = request.GET.get('sort_by')
    search = request.GET.get('search')
    amenities = request.GET.getlist('amenities')
    if sort_by:
        if sort_by == 'ASC':
            hotels_objs = hotels_objs.order_by('hotel_price')
        elif sort_by == 'DSC':
            hotels_objs = hotels_objs.order_by('-hotel_price')

    if search:
        hotels_objs = hotels_objs.filter(
            Q(hotel_name__icontains = search) |
            Q(description__icontains = search) )


    if len(amenities):
        hotels_objs = hotels_objs.filter(amenities__amenity_name__in = amenities).distinct()

    context = {
        'amenities_objs' : amenities_objs , 
        'hotels_objs' : hotels_objs , 
        'sort_by' : sort_by ,
        'search' : search , 
        'amenities' : amenities
    }

    # return render(request , 'home.html' ,context)

home/templates/about_us.html
{% extends 'base2.html' %}
{% block content %}
    <div class="container  justify-content-center pt-5 container align-items-center pt-5 shadow-lg p-3 mt-5 mb-5 bg-body-white rounded">
        <h1>About Us</h1>
        <p>[Hotel Booking App Name] is a comprehensive hotel booking app that helps users to easily find and book their ideal hotel accommodations. Our app offers a wide range of hotels across the world, with detailed information about each property, including amenities, prices, and user ratings.</p>
        <p>Our mission is to simplify the hotel booking process and make it more accessible to everyone. We strive to provide the best possible service to our users and ensure that they have a hassle-free and enjoyable experience while using our app.</p>
        <p>At [Hotel Booking App Name], we believe in transparency and honesty, and we are committed to providing accurate and up-to-date information about all the hotels listed on our app. We work hard to ensure that our users can trust us to help them find the best hotel accommodations at the best prices.</p>
    </div>
    
{% endblock %}

home/templates/booking_detail.html
{% extends 'base2.html' %}

{% block content %}
<div
  class="container  justify-content-center pt-5 container align-items-center pt-5 shadow-lg p-3 mt-5 mb-5 bg-body-white rounded">
  <h2 class="text-secondary">Booking Detail</h2>
  <hr>
  <figure class="">
    <figcaption class="blockquote text-danger">
      *Please Check following information<cite title="Source Title"> Carefully</cite>
    </figcaption>
  </figure>
  <div class="row">
    <div class="col-4 ">
      <h3 class="text-secondary">Hotel Detail </h3>
      <hr>
      <h5 class="text-secondary">Hotel Name: {{ booking.hotel.hotel_name }}</h5>
      <p>Check In: {{ booking.start_date }}</p>
      <p>Check Out: {{ booking.end_date }}</p>
      <p>Booking Type: {{ booking.booking_type }}</p>
      <p>Person Details: {{booking.customer_desc}}</p>
      <p>Room : {{booking.room_type}}</p>
      <p>Total Booked Rooms : {{ booking.no_of_room }}</p>
      <p>Allotted Room Numbers: {{ booking.room_number }}</p>
      <h4 class="text-secondary">Total Amount: {{booking.amount}} </h4>
      <div class="container pt-2">
        <form action="{% url 'payment:checkout-session' uid %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-dark">Proceed to Pay</button>
        </form>
  
      </div>
    </div>
    <div class="col-4">
      <h3 class="text-secondary"> Customer Detail  </h3>
      <hr>
      <h4 class="text-secondary">Name: {{booking.user.username}}</h4>
      <h5 class="text-secondary">Email: {{booking.user.email}}</h5>
      <h5 class="text-secondary">Phone: 987610</h5>
    </div>
    <div class="col-4">
      <div class="container text-center ">        
        <div class="row">
            {% for image in booking.hotel.images.all|slice:":4" %}
            <div class="col-6">
                <div class="gallery_img">
                    <figure><img src="/media/{{image.images}}" alt="#" /></figure>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

  </div>

</div>
{% endblock %}

home/templates/booking_form.html
{% extends 'base2.html' %}

{% block content %}
<div class="container justify-content-center align-items-center pt-5 shadow-lg p-3 mt-5 mb-5 bg-body-white rounded">
  <h2 class="text-secondary text-center">Book a Room at <span class="text-warning"> {{ hotel.hotel_name }}</span></h2>
  {% include 'messages.html' %}
  <hr>
  <div class="row">
    <div class="col-6">
      <figure class="">
        <figcaption class="blockquote text-danger">
          *Please fill below<cite title="Source Title"> information carefully</cite>
        </figcaption>
      </figure>
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="uid" id="uid" value="{{ hotel.uid }}">
        <div class="form-group">
          <label for="start_date">Start Date:</label>
          <input type="date" name="start_date" id="start_date" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="end_date">End Date:</label>
          <input type="date" name="end_date" id="end_date" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="room_type">Room Type:</label>
          <select name="room_type" id="room_type" class="form-control" required>
            {% for room_type in room_type %}
            <option value="{{ room_type}}">{{ room_type }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="booking_type">Booking Type:</label>
          <select name="booking_type" id="booking_type" class="form-control" required>
            <option value="Pre Paid">Pre Paid</option>
            <option value="Post Paid">Post Paid</option>
          </select>
        </div>
        <div class="form-group">
          <label for="no_of_room">Number of Rooms:</label>
          <input type="number" name="no_of_room" id="no_of_room" class="form-control" value="1" min="1" required>
        </div>
        <div class="form-group">
          <label for="no_of_people">Total Person:</label>
          <input type="number" name="no_of_people" id="no_of_people" class="form-control" value="1" min="1" required>
        </div>
        <div class="form-group">
          <label for="customer_desc">Persons Details:</label>
          <select name="customer_desc" id="customer_desc">
            <option value="1 adults, 0 child">1 adults, 0 child</option>
            <option value="1 adults, 1 child">1 adults, 1 child</option>
            <option value="2 adults, 0 child">2 adults, 0 child</option>
            <option value="2 adults, 1 child">2 adults, 1 child</option>
            <option value="2 adults, 2 child">2 adults, 2 child</option>
            <option value="All Adults">All Adults</option>
            <option value="Others">Others</option>
          </select>
        </div>

        <button type="submit" class="btn btn-warning">Book Now</button>

      </form>
    </div>
    <div class="col-6">
      <div class="container text-center ">
        
        <div class="row">
            {% for image in hotel.images.all|slice:":4" %}
            <div class="col-6">
                <div class="gallery_img">
                    <figure><img src="/media/{{image.images}}" alt="#" /></figure>
                </div>
            </div>

            {% endfor %}

            <div class="ps-2">
              <small class="">Rating: </small>
              <small class="fa fa-star text-dark"></small>
              <small class="fa fa-star text-dark"></small>
              <small class="fa fa-star text-dark"></small>
              <small class="fa fa-star text-dark"></small>
              <small class="fa fa-star text-dark"></small>
          </div>

        </div>
    </div>
  </div>
</div>
{% endblock %}

home/templates/contact_us.html
{% extends 'base2.html' %}
{% block content %}
<title>Contact Us - [Hotel Booking App Name]</title>

<div class="container  justify-content-center pt-5 container align-items-center pt-5 shadow-lg p-3 mt-5 mb-5 bg-body-white rounded">
<h1>Contact Us</h1>
<p>If you have any questions, comments, or concerns about [Hotel Booking App Name], please don't hesitate to contact us. We are always happy to hear from our users and are committed to providing the best possible customer service.</p>
<h2>Contact Information:</h2>
<ul>
  <li>Email: contact@motelo.com</li>
  <li>Phone: 9876543210</li>
  <li>Social Media: </li>
</ul>
<p>We also have a dedicated customer support team available 24/7 to assist you with any issues you may have. You can reach them by clicking on the "Support" button within the app or by sending an email to [Insert Email Address].</p>
<p>Thank you for choosing [Hotel Booking App Name], and we look forward to hearing from you soon!</p>
</div>
{% endblock %}

home/templates/navbar.html
{% load static %}

<div class="header__nav__option">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="header__logo">
                    <a href="{% url 'home:home' %}"><img src="{% static 'images/motelo-logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-10">
                <div class="header__nav">
                    <nav class="header__menu">
                        <ul class="menu__class " style=" font-weight:20px">
                            <li class="active"><a href="{% url 'home:home' %}">Home</a></li>

                            <li><a href="#" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Pages</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'home:about_us' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">About Us</a></li>   

                                    <li><a href="{% url 'home:about_us' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Blogs</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'home:about_us' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">News</a></li>
                            
                            <li><a href="{% url 'home:contact_us' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Contact Us</a></li>
                            {% if request.user.is_authenticated %} 
                           
                            <li><a href="#"><button class="btn btn-dark text-warning" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">{{request.user}}</button></a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'profile' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover me-auto">Profile</a></li>                                      
                                    <li><a href="{% url 'payment:booking-history' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Bookings</a></li>
                                </ul>
                            </li>
                            {% else %}
                            <li><a href="{% url 'signin' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Log In</a></li>
                            <li><a href="{% url 'signup' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Register</a></li>
                            {% endif %}                            
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
        <div class="canvas__open">
            <span class="fa fa-bars"></span>
        </div> 
    </div>
</div>


<div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
    <div class="offcanvas-header">
      <h4 class="offcanvas-title" id="offcanvasScrollingLabel">{{request.user}} </h4>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <li class="nav-link"><a href="{% url 'profile' %}" >Profile</a></li>
        <li><a href="{% url 'payment:booking-history' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Bookings</a></li>
        <li><a href="{% url 'signout' %}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">Logout</a></li>
        
    </div>
  </div>